### ISSUE TITLE
Dodatkowy rezystor na PCB (modyfikacja hand-made)

### ISSUE THREAD

**Issue by PiotrKazimierzWiacek** [alice-fit-fee-upgrade/FIT_PM12_PCB#1]
Przecięcie ścieżki i dołożenie rezystora (TopLayer, wartość rezystancji 75R (?) - do potwierdzenia na podstawie wylutu i pomiarze!!!)
Poprawa w każdym kanale.
![obraz3](https://github.com/alice-fit-fee-upgrade/FIT_PM12_PCB/assets/150081866/e1dafc12-b005-4257-8e6f-b70973813c98)

**Comment by gkasprow** [comment]
on jest w dokumentacji jako R300 = 100Ohm

**Comment by PiotrKazimierzWiacek** [comment]
W wersji pierwotnej z 21.06.2024 na której mieliśmy pracować jeszcze tego rez. nie było. Faktycznie na obecnych plikach źródłowych już rezystor jest. OK
