### ISSUE TITLE
Dodatkowy rezystor na PCB, BottomL (modyfikacja hand-made)

### ISSUE THREAD

**Issue by PiotrKazimierzWiacek** [alice-fit-fee-upgrade/FIT_PM12_PCB#2]
Przecięcie ścieżki i dołożenie rezystora (BottomLayer, wartość rezystancji 75R (?) - do potwierdzenia na podstawie wylutu i pomiarze!!!)
Poprawa w każdym kanale.
![obraz4](https://github.com/alice-fit-fee-upgrade/FIT_PM12_PCB/assets/150081866/905da245-8d87-4d36-bf12-3948b4cbfcb0)

**Comment by gkasprow** [comment]
on jest w projekcie jako R400 = 100Ohm

**Comment by PiotrKazimierzWiacek** [comment]
W wersji pierwotnej z 21.06.2024 na której mieliśmy pracować jeszcze tego rez. nie było. Faktycznie na obecnych plikach źródłowych już rezystor jest. OK
