### ISSUE TITLE
Dodatkowy kondensator na wej. integratorów (modyfikacja hand-made)

### ISSUE THREAD

**Issue by PiotrKazimierzWiacek** [alice-fit-fee-upgrade/FIT_PM12_PCB#3]
Dołożenie kondensatora (TopLayer, wartość pojemności 220nF (?) - do potwierdzenia na podstawie wylutu i pomiarze!!!)
Poprawa w każdym kanale
![obraz5](https://github.com/alice-fit-fee-upgrade/FIT_PM12_PCB/assets/150081866/a8fe63e2-ed1d-430a-b52d-90f1185ddb0f)

**Comment by gkasprow** [comment]
mamy go juz w projekcie jako C304=100nF
![image](https://github.com/user-attachments/assets/0bd8cdce-9fd0-41fc-b437-476990a83fc2)

**Comment by PiotrKazimierzWiacek** [comment]
W wersji pierwotnej z 21.06.2024 na której mieliśmy pracować jeszcze tego cap. nie było. Faktycznie na obecnych plikach źródłowych już kondensator jest. OK
