### ISSUE TITLE
Bledna wartosc resytancji R13, R19, R33, R38

### ISSUE THREAD

**Issue by PiotrKazimierzWiacek** [alice-fit-fee-upgrade/FIT_PM12_PCB#4]
Bledna wartosc resytancji R13, R19, R33, R38 na PM12 (w kazdym kanale z osobna).
W projekcie PM12 dla komponentow indywidualnie w kazdym kanale: R13, R19, R33, R38 zastosowano wartość rezystancji 220R. Na płycie udostępnionej przez CERN (wariant pod FV0) rezystancja przedmiotowych rezystorow wynosi **430R**
![obraz6](https://github.com/alice-fit-fee-upgrade/FIT_PM12_PCB/assets/150081866/d08b3471-2169-48ab-9019-568bab4e950c)

**Comment by gkasprow** [comment]
czy ich wartosc nie rozni sie w zaleznosci od waruantu?
To rezystory konwertujace napiecie na prad i wplywajace na stałą przetwarzania integratora

**Comment by PiotrKazimierzWiacek** [comment]
Na obecną chwilę niech zostaną 220R, te rez. modyfikują stałą czasową integratora. Ewentualnie będziemy je modyfikować przy testach.
